---
hostname: tkanemoto.com
hostname_short: '{{ hostname | regex_replace("\..*$", "") }}'
allowed_csp_domains:
  - 'https://www.instagram.com'
  - 'https://fonts.gstatic.com'
  - 'https://www.google-analytics.com'
  - 'https://www.googletagmanager.com'
  - 'https://cdnjs.cloudflare.com'
  - 'https://www.google.com'
  - 'https://www.gstatic.com'
  - 'https://platform.twitter.com'
  - 'https://syndication.twitter.com'
  - 'https://platform.linkedin.com'
  - 'https://connect.facebook.net'
  - 'https://snap.licdn.com'
  - 'https://static.ads-twitter.com'
  - 'https://px.ads.linkedin.com'
  - 'https://analytics.twitter.com'
  - 'https://www.linkedin.com'
  - 'https://www.henrisalonen.com'

cloudflare_ips:
  - '173.245.48.0/20'
  - '103.21.244.0/22'
  - '103.22.200.0/22'
  - '103.31.4.0/22'
  - '141.101.64.0/18'
  - '108.162.192.0/18'
  - '190.93.240.0/20'
  - '188.114.96.0/20'
  - '197.234.240.0/22'
  - '198.41.128.0/17'
  - '162.158.0.0/15'
  - '104.16.0.0/12'
  - '172.64.0.0/13'
  - '131.0.72.0/22'

znc_port: 8667
znc_datadir: /var/lib/znc
znc_service: true
znc_ssl: true
znc_system_modules:
  - webadmin
znc_user_name: admin
znc_user_password: 'sha256#6c7ca980f175a5b5c0c02f3b26e77637d9c50b7ca7b2181eb96acf766fe40c27#xJ/eJ_;!SKR;4)z3e)P5#'
znc_user_nick: PenguinNomad
znc_user_altnick: T4K
znc_user_realname: 'Takeshi Kanemoto'
#znc_force_config_refresh: true
#znc_user_module: chansaver controlpanel

apache_global_vhost_settings: |
  DirectoryIndex index.php index.html
  LogLevel warn
  #LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\" %D %B" {{ hostname_short }}_access
  #LogFormat "%v:%p %h %l %u %t \"%r\" %>s %D \"%{Referer}i\" \"%{User-Agent}i\"" {{ hostname_short }}_access
  #CustomLog /var/log/apache2/{{ hostname }}_access.log {{ hostname_short }}_access
  ErrorLog /var/log/apache2/error.log

django_site_root: /var/www/django-site
django_site_manifest_url: https://github.com/tkanemoto/django-manifest.git
django_database_db: django
django_database_username: django

apache_remove_default_vhost: true
#apache_vhosts_filename: '000-vhosts.conf'
apache_create_vhosts: false
apache_mods_enabled:
  - rewrite.load
  - proxy.load
  - proxy_http.load
  - proxy_wstunnel.load
  - wsgi.load
  - headers.load
  - reqtimeout.load
  - ssl.load
  - php7.2.load
  - oauth2.load
apache_packages:
  - apache2
  - apache2-utils
  - apache2-dev
  - libapache2-mod-php

apache_vhosts:
  - servername: 'apps.{{ hostname }}'
    documentroot: '{{ django_site_root }}/htdocs'
    extra_parameters: |
      RewriteEngine on
      RewriteRule ^/review/(.*)$ https://review.%{SERVER_NAME}/$1 [R=301,L]
      RewriteRule ^/ci/(.*)$ https://ci.%{SERVER_NAME}/$1 [R=301,L]
      RewriteRule ^/?(.*)$ https://%{SERVER_NAME}/$1 [R=301,L]

  - servername: 'tkanemoto-review.ddns.net'
    documentroot: '{{ django_site_root }}/htdocs'
    extra_parameters: |
      RewriteEngine on
      RewriteCond %{HTTP_USER_AGENT}  ^curl/.*
      RewriteRule ^/review/a/projects/ota-packages/branches/master/files/ota.sh/content https://{{ hostname }}/static/public/ota.sh [R=301,L]
      RewriteRule ^/?(.*)$ https://review.{{ hostname }}/$1 [R=301,L]

  - servername: 'tkanemoto.ddns.net'
    documentroot: '{{ django_site_root }}/htdocs'
    extra_parameters: |
      RewriteEngine on
      RewriteCond %{HTTP_USER_AGENT}  ^curl/.*
      RewriteRule ^/review/a/projects/ota-packages/branches/master/files/ota.sh/content https://{{ hostname }}/static/public/ota.sh [R=301,L]
      RewriteRule ^/?(.*)$ https://{{ hostname }}/$1 [R=301,L]

apache_vhosts_ssl:
  - servername: 'apps.{{ hostname }}'
    documentroot: '{{ django_site_root }}/htdocs'
    certificate_file: '/etc/ssl/certs/{{ hostname }}.pem'
    certificate_key_file: '/etc/ssl/private/{{ hostname }}.key'
    extra_parameters: |
      Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains; preload"
      RequestReadTimeout header=90,MinRate=500 body=90,MinRate=500
      WSGIDaemonProcess django \
        user=django \
        group=django \
        processes=1 \
        threads=15 \
        display-name=%{GROUP} \
        python-home={{ django_site_root }}/.virtualenv \
        python-path={{ django_site_root }}/site
      WSGIProcessGroup django
      WSGIScriptAlias / {{ django_site_root }}/site/project/wsgi.py process-group=django

      RewriteEngine on
      #RewriteRule ^/review/(.*)$ https://review.%{SERVER_NAME}/$1 [R=301,L]
      #RewriteRule ^/ci/(.*)$ https://ci.%{SERVER_NAME}/$1 [R=301,L]

      Alias /static/ {{ django_site_root }}/static/
      <Directory "{{ django_site_root }}/static">
        AllowOverride All
        Options -Indexes +FollowSymLinks
        Require all granted
        Header set Access-Control-Allow-Origin "*"
      </Directory>
      <Location ~ "^/(media/|static/|google{{ google_site_verification_code }}\.html)">
        <RequireAny>
          {% for ip in cloudflare_ips %}
            Require ip {{ ip }}
          {% endfor %}
        </RequireAny>
        Satisfy Any
      </Location>

      Alias /media/ {{ django_site_root }}/static/media/
      Alias /google{{ google_site_verification_code }}.html {{ django_site_root }}/htdocs/google{{ google_site_verification_code }}.html

      RewriteCond %{HTTP:Upgrade} =websocket [NC]
      RewriteRule /(.*)           ws://localhost:9876/$1 [P,L]

      <Location />
        AuthType oauth2
        OAuth2TokenVerify jwks_uri https://tkanemoto.cloudflareaccess.com/cdn-cgi/access/certs jwks_uri.ssl_verify=false&verify.iat.slack_before=90000
        OAuth2AcceptTokenIn cookie name=CF_Authorization
        OAuth2TargetPass prefix=cf-access-claim-&authn_header=REMOTE_USER
        <RequireAll>
          <RequireAny>
            {% for ip in cloudflare_ips %}
              Require ip {{ ip }}
            {% endfor %}
          </RequireAny>
          Require valid-user
        </RequireAll>
      </Location>
      {{ apache_extra_parameters }}

  - servername: 'ci.{{ hostname }}'
    documentroot: '{{ django_site_root }}/htdocs'
    certificate_file: '/etc/ssl/certs/{{ hostname }}.pem'
    certificate_key_file: '/etc/ssl/private/{{ hostname }}.key'
    extra_parameters: |
      LimitRequestFieldSize 32760
      LimitRequestLine 32760
      Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains; preload"
      Header set Content-Security-Policy "script-src 'self' 'unsafe-inline' 'unsafe-eval' {{ allowed_csp_domains | join(' ') }}"
      ProxyPreserveHost On
      ProxyRequests     Off
      AllowEncodedSlashes NoDecode

      <Location ~ "^/computer/.*/.*.jnlp">
        <RequireAny>
          {% for ip in cloudflare_ips %}
            Require ip {{ ip }}
          {% endfor %}
        </RequireAny>
      </Location>
      <Location /wsagents/>
        RewriteEngine on
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule .* ws://{{ groups['jenkins'][0] }}:{{ jenkins_http_port }}/%{REQUEST_URI} [P,L]
        <RequireAny>
          {% for ip in cloudflare_ips %}
            Require ip {{ ip }}
          {% endfor %}
        </RequireAny>
      </Location>
      <Location ~ "^/(tcpSlaveAgentListener|jnlpJars|github-webhook)/">
        <RequireAny>
          {% for ip in cloudflare_ips %}
            Require ip {{ ip }}
          {% endfor %}
        </RequireAny>
      </Location>

      <Proxy *>
        AuthType oauth2
        OAuth2TokenVerify jwks_uri https://tkanemoto.cloudflareaccess.com/cdn-cgi/access/certs jwks_uri.ssl_verify=false&verify.iat.slack_before=90000
        OAuth2AcceptTokenIn cookie name=CF_Authorization
        OAuth2TargetPass prefix=cf-access-claim-&authn_header=REMOTE_USER
        RequestHeader unset X-Forwarded-User
        RewriteEngine On
        RewriteCond %{LA-U:REMOTE_USER} (.+)
        RewriteRule .* - [E=RU:%1,NS]
        RequestHeader set X-Forwarded-User cf-access-%{RU}e
        <RequireAll>
          <RequireAny>
            {% for ip in cloudflare_ips %}
              Require ip {{ ip }}
            {% endfor %}
          </RequireAny>
          Require valid-user
        </RequireAll>
        ErrorDocument 401 "<html><meta http-equiv=\"refresh\" content=\"0;url=https://tkanemoto.cloudflareaccess.com/\"></html>"
      </Proxy>

      ProxyPass / http://{{ groups['jenkins'][0] }}:{{ jenkins_http_port }}/ nocanon
      ProxyPassReverse / http://{{ groups['jenkins'][0] }}:{{ jenkins_http_port }}/

  - servername: 'review.{{ hostname }}'
    documentroot: '{{ django_site_root }}/htdocs'
    certificate_file: '/etc/ssl/certs/{{ hostname }}.pem'
    certificate_key_file: '/etc/ssl/private/{{ hostname }}.key'
    extra_parameters: |
      Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains; preload"
      #Alias /clone-bundles {{ django_site_root }}/htdocs/clone-bundles
      #RewriteEngine on
      #RewriteRule ^/a/(.*)\.git/clone.bundle$ https://{{ hostname }}/static/public/clone-bundles/$1.git/clone.bundle [R=301,L]
      #RewriteRule ^/a/(.*)/clone.bundle$ https://{{ hostname }}/static/public/clone-bundles/$1.git/clone.bundle [R=301,L]
      <Location />
        AuthType oauth2
        OAuth2TokenVerify jwks_uri https://tkanemoto.cloudflareaccess.com/cdn-cgi/access/certs jwks_uri.ssl_verify=false&verify.iat.slack_before=90000
        OAuth2AcceptTokenIn cookie name=CF_Authorization
        OAuth2TargetPass prefix=cf-access-claim-&authn_header=REMOTE_USER
        RequestHeader unset REMOTE_USER
        RewriteEngine On
        RewriteCond %{LA-U:REMOTE_USER} (.+)
        RewriteRule .* - [E=RU:%1,NS]
        RequestHeader set REMOTE_USER cf-access-%{RU}e
        <RequireAll>
          <RequireAny>
            {% for ip in cloudflare_ips %}
              Require ip {{ ip }}
            {% endfor %}
          </RequireAny>
          Require valid-user
        </RequireAll>
      </Location>

      ProxyPreserveHost On
      ProxyRequests     Off
      #ProxyVia Off
      AllowEncodedSlashes NoDecode
      ProxyPass / http://{{ groups['gerrit'][0] }}:8081/ nocanon
      ProxyPassReverse / http://{{ groups['gerrit'][0] }}:8081/

  - servername: 'irc.{{ hostname }}'
    documentroot: '{{ znc_datadir }}'
    certificate_file: '/etc/ssl/certs/{{ hostname }}.pem'
    certificate_key_file: '/etc/ssl/private/{{ hostname }}.key'
    extra_parameters: |
      Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains; preload"
      SSLProxyEngine on
      SSLProxyVerify none
      SSLProxyCheckPeerCN off
      SSLProxyCheckPeerName off
      ProxyPreserveHost On
      ProxyRequests     On
      #AllowEncodedSlashes NoDecode
      ProxyPass / https://127.0.0.1:{{ znc_port }}/
      ProxyPassReverse / https://127.0.0.1:{{ znc_port }}/
      <Location />
        AuthType oauth2
        OAuth2TokenVerify jwks_uri https://tkanemoto.cloudflareaccess.com/cdn-cgi/access/certs jwks_uri.ssl_verify=false&verify.iat.slack_before=90000
        OAuth2AcceptTokenIn cookie name=CF_Authorization
        <RequireAll>
          <RequireAny>
            {% for ip in cloudflare_ips %}
              Require ip {{ ip }}
            {% endfor %}
          </RequireAny>
          Require valid-user
        </RequireAll>
      </Location>

  # - servername: 'files.{{ hostname }}'
  #   documentroot: '/var/www/owncloud'
  #   certificate_file: '/etc/letsencrypt/live/files.{{ hostname }}/cert.pem'
  #   certificate_key_file: '/etc/letsencrypt/live/files.{{ hostname }}/privkey.pem'
  #   certificate_chain_file: '/etc/letsencrypt/live/files.{{ hostname }}/fullchain.pem'
  #   extra_parameters: |
  #     Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains; preload"

  - servername: 'source.{{ hostname }}'
    documentroot: '{{ django_site_root }}/htdocs'
    certificate_file: '/etc/ssl/certs/{{ hostname }}.pem'
    certificate_key_file: '/etc/ssl/private/{{ hostname }}.key'
    extra_parameters: |
      Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains; preload"
      ProxyPass /xref http://127.0.0.1:8080/xref nocanon
      ProxyPassReverse /xref http://127.0.0.1:8080/xref
      <Location />
        AuthType Basic
        AuthName "Restricted"
        AuthBasicProvider file
        AuthUserFile "{{ django_site_root }}/htpasswd"
        Require valid-user
      </Location>

  - servername: 'updates.{{ hostname }}'
    documentroot: '{{ django_site_root }}/htdocs'
    certificate_file: '/etc/ssl/certs/{{ hostname }}.pem'
    certificate_key_file: '/etc/ssl/private/{{ hostname }}.key'
    extra_parameters: |
      Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains; preload"
      {{ updates_apache_config }}
