---
gerrit_version: '2.12'
gerrit_sha256sum: '8f2e2e61b939664a20a025ef4f99095c08be14342ea5457bf5613bccedabcd27'
gerrit_canonical_web_url: 'http://tkanemoto.ddns.net/review/'
gerrit_httpd_listen_url: "proxy-http://*:8081/review/"
gerrit_database_type: 'postgresql'
gerrit_database_db: gerritdb
gerrit_database_username: 'gerrit'
# gerrit_database_password: defined in encrypted_vars
gerrit_sendmail_smtp_server: smtp.gmail.com
gerrit_core_packed_git_open_files: 32000
