---
gerrit_version: '3.1.0'
gerrit_sha256sum: d8e39297c53652f5b9075f5a2493c9ef49a383151eff49d2fb366bb42011759b
#gerrit_download_server: 'https://www.gerritcodereview.com/download'

#gerrit_version: '2.15'
#gerrit_sha256sum: 7c07ce361d05212511097c8f635c7b60fb0c1e3c8be8c8f8b8fa1c4655f42d9e
#gerrit_download_server: https://gerrit-releases.storage.googleapis.com

gerrit_canonical_web_url: 'https://review.tkanemoto.com/'
gerrit_httpd_listen_url: "proxy-https://*:8081/"
gerrit_database_type: 'postgresql'
gerrit_database_db: gerritdb
gerrit_database_username: 'gerrit'
# gerrit_database_password: defined in encrypted_vars
gerrit_sendemail_smtp_server: smtp.mailgun.org
#gerrit_auth_type: OAUTH
gerrit_auth_type: HTTP

gerrit_extra_config_list:
  - { section: core, option: packedGitOpenFiles, value: 4096 }
  - { section: core, option: packedGitLimit, value: '10m' }
  - { section: core, option: packedGitWindowSize, value: '8k' }
  - { section: container, option: javaOptions, value: '-XX:+UseG1GC -Xmx3g -XX:+UseStringDeduplication' }
  - { section: gerrit, option: serverId, value: 'ef990535-4474-414b-a9cb-f7c3b97803cc' }
  #- { section: 'plugin "gerrit-oauth-provider-google-oauth"', option: 'client-id', value: '932815769348-6d1ijbvtshaeerj648gn0ir5jdncoqbk.apps.googleusercontent.com' }
  #- { section: 'plugin "gerrit-oauth-provider-google-oauth"', option: 'link-to-existing-openid-accounts', value: 'true' }
  #- { section: 'plugin "gerrit-oauth-provider-github-oauth"', option: 'client-id', value: '915b01ff9294158cb16d' }
  - { section: auth, option: gitBasicAuthPolicy, value: HTTP }
  - { section: auth, option: httpHeader, value: REMOTE_USER }
  - { section: auth, option: loginUrl, value: 'https://tkanemoto.cloudflareaccess.com/' }
  - { section: auth, option: logoutUrl, value: 'https://tkanemoto.cloudflareaccess.com/cdn-cgi/access/logout?returnTo=https://review.tkanemoto.com/' }
  - { section: auth, option: registerPageUrl, value: '/' }
  - { section: auth, option: allowRegisterNewEmail, value: 'true' }
  - { section: change, option: largeChange, value: 2000 }
  - { section: changeCleanup, option: abandonAfter, value: 1y }
  - { section: changeCleanup, option: startTime, value: '06:00' }
  - { section: changeCleanup, option: interval, value: '1 day' }
  - { section: gc, option: startTime, value: '01:30' }
  - { section: gc, option: interval, value: '7 day' }
  - { section: gc, option: aggressive, value: 'true' }
  - { section: download, option: command, value: checkout }
  - { section: download, option: scheme, value: http }
  - { section: sendemail, option: smtpEncryption, value: ssl }
  - { section: sendemail, option: smtpServerPort, value: 465 }
  - { section: sendemail, option: smtpUser, value: 'postmaster@tkanemoto.com' }
  - { section: sendemail, option: includeDiff, value: 'true' }

gerrit_service_after: syslog.target network.target mnt-share.mount postgresql.service