---
gerrit_version: '2.12.2'
gerrit_sha256sum: 'ff28bd84a078534b4fd1bf2e3e8b38cde5437c28e25c1e0a33dbcdf2182bbff7'
gerrit_download_server: 'https://www.gerritcodereview.com/download'
gerrit_canonical_web_url: 'https://review.tkanemoto.com/'
gerrit_httpd_listen_url: "proxy-https://*:8081/"
gerrit_database_type: 'postgresql'
gerrit_database_db: gerritdb
gerrit_database_username: 'gerrit'
# gerrit_database_password: defined in encrypted_vars
gerrit_sendmail_smtp_server: smtp.gmail.com
gerrit_core_packed_git_open_files: 32000
gerrit_auth_type: OAUTH
gerrit_extra_gerrit_config: |
  [plugin "gerrit-oauth-provider-google-oauth"]
          client-id = 932815769348-6d1ijbvtshaeerj648gn0ir5jdncoqbk.apps.googleusercontent.com
          link-to-existing-openid-accounts = true
  [plugin "gerrit-oauth-provider-github-oauth"]
          client-id = 915b01ff9294158cb16d