---
- hosts: apache
  become: yes

  vars_files:
    - encrypted_vars/apache.yml

  roles:
    - { role: django-site }
    - { role: tkanemoto.owncloud }
    - { role: geerlingguy.apache }
    - { role: tkanemoto.transmission-rss }
    - { role: geerlingguy.nodejs }
    - { role: tkanemoto.nodejs-systemd }
