---
- hosts: apache
  user: ubuntu
  sudo: yes
  vars:
    apache_listen_port: 80
    apache_remove_default_vhost: true
    apache_mods_enabled:
      - rewrite.load
      - proxy.load
      - proxy_http.load
      - wsgi.load
    apache_packages:
      - apache2
      - apache2-utils
      - libapache2-mod-wsgi
    apache_vhosts:
      - servername: "tkanemoto.ddns.net"
        documentroot: "/var/www/django-site/htdocs"
        extra_parameters: |
          AllowEncodedSlashes NoDecode
          RewriteEngine on
          ProxyPass /review http://127.0.0.1:8081/review nocanon
          ProxyPassReverse /review http://localhost:8081/review
          ProxyPass /ci http://127.0.0.1:8080/ci nocanon
          ProxyPassReverse /ci http://localhost:8080/ci
          ProxyPass /transmission/ http://127.0.0.1:29091/transmission nocanon
          ProxyPassReverse /transmission http://localhost:29091/transmission
          Alias /static/ /var/www/django-site/static/
          <Directory "/var/www/django-site/static">
            AllowOverride All
            Options +Indexes +FollowSymLinks
            Require all granted
          </Directory>
          Alias /media/ /var/www/django-site/static/media/
          ProxyPass /share/ http://127.0.0.1:28003/share/
          ProxyPassReverse /share/ http://localhost:28003/share/
          WSGIDaemonProcess django \
            user=django \
            group=django \
            processes=4 \
            threads=15 \
            display-name=%{GROUP} \
            python-path=/var/www/django-site/site:/var/www/django-site/.virtualenv/lib/python2.7/site-packages
          WSGIProcessGroup django
          WSGIScriptAlias / /var/www/django-site/site/project/wsgi.py
    django_site_root: /var/www/django-site
    django_site_manifest_url: https://github.com/tkanemoto/django-manifest.git
    django_database_db: django
    django_database_username: django

  vars_files:
    - encrypted_vars/apache.yml

  roles:
    - { role: django-site }
    - { role: geerlingguy.apache }
