---
- hosts: apache
  become: yes

  vars_files:
    - encrypted_vars/apache.yml

  roles:
    - { role: tkanemoto.transmission-rss }
    - { role: geerlingguy.nodejs }
    - { role: tkanemoto.nodejs-systemd }
    - { role: willshersystems.znc }
