---
- hosts: gerrit
  become: yes

  vars_files:
    - encrypted_vars/gerrit.yml

  roles:
    - { role: kbrebanov.gerrit }

  pre_tasks:
    - name: Make sure Python3 Psycopg2 is installed
      apt: name={{ item }} update_cache=yes state=installed
      with_items:
        - python3-psycopg2

  post_tasks:
    - name: Hint that gerrit should start after postgresql
      lineinfile: >
        dest={{ gerrit_site_dir }}/bin/gerrit.sh
        regexp="^# Should-Start:"
        line="# Should-Start:      postgresql"
        insertafter="^# Required-Stop"
      when: false

    - name: Hint that gerrit should start after postgresql
      lineinfile: >
        dest={{ gerrit_site_dir }}/bin/gerrit.sh
        regexp="^# Should-Stop:"
        line="# Should-Stop:       postgresql"
        insertafter="^# Required-Start"
      when: false
