---
- hosts: gerrit
  user: ubuntu
  sudo: yes
  vars:
    gerrit_version: '2.11.3'
    gerrit_sha256sum: '3ec7998a7307e54cabacfdb04882d2852727bb341bf058a6a2beadd8f750a910'
    gerrit_canonical_web_url: 'http://tkanemoto.ddns.net/review/'
    gerrit_httpd_listen_url: 'http://{{ ansible_all_ipv4_addresses[0] }}:8081/review/'
    gerrit_database_type: 'postgresql'
    gerrit_database_db: gerritdb
    gerrit_database_username: 'gerrit'
    # gerrit_database_password: defined in encrypted_vars
    gerrit_sendmail_smtp_server: smtp.gmail.com

  vars_files:
    - encrypted_vars/gerrit.yml

  roles:
    - { role: kbrebanov.gerrit }
