---
- hosts: jenkins
  become: yes

  vars_files:
    - encrypted_vars/jenkins.yml

  pre_tasks:
    - name: Check if Jenkins already instealld
      shell: dpkg-query -W 'jenkins'
      ignore_errors: true
      register: has_jenkins

    # Work around https://github.com/geerlingguy/ansible-role-jenkins/issues/47
    - name: Fetch Jenkins 1.658
      get_url:
        url: https://pkg.jenkins.io/debian/binary/jenkins_1.658_all.deb
        dest: /var/lib/jenkins_1.658_all.deb
        checksum: sha256:8cf15cd5d107dedd6380fed15f6f157819544ab698eea6a1dcb3b8c98a9352b7
      when: not has_jenkins

    - name: Install Jenkins 1.658
      apt: deb=/var/lib/jenkins_1.658_all.deb
      when: not has_jenkins

  roles:
    - geerlingguy.jenkins

  post_tasks:
    - name: Inject passwords
      lineinfile:
        dest: '/var/lib/jenkins/.netrc'
        line: 'machine {{ item.machine }} login {{ item.login }} password {{ item.password }}'
        regexp: '^machine {{ item.machine }}'
        state: present
        owner: jenkins
        group: jenkins
        mode: 0600
        create: yes
      with_items: '{{ jenkins_netrc_entries }}'
