---
- hosts: jenkins
  become: yes

  pre_tasks:
    # Work around https://github.com/geerlingguy/ansible-role-jenkins/issues/47
    - name: Fetch Jenkins 1.658
      get_url:
        url: http://pkg.jenkins-ci.org/debian/binary/jenkins_1.658_all.deb
        dest: /tmp/jenkins_1.658_all.deb

    - name: Install Jenkins 1.658
      apt: deb=/tmp/jenkins_1.658_all.deb

  roles:
    - geerlingguy.jenkins
