---
- name: Adjust vm.swappiness sysctl setting
  sysctl:
    name=vm.swappiness
    value={{ sysctl_swappiness }}
    state=present
    sysctl_set=yes
    sysctl_file=/etc/sysctl.d/99-tkserver.conf

- name: Adjust vm.vfs_cache_pressure sysctl setting
  sysctl:
    name=vm.vfs_cache_pressure
    value={{ sysctl_vfs_cache_pressure }}
    state=present
    sysctl_set=yes
    sysctl_file=/etc/sysctl.d/99-tkserver.conf

