---
- name: Include OS-specific variables.
  include_vars: "roles/geerlingguy.apache/vars/{{ ansible_os_family }}.yml"

# Figure out what version of Apache is installed.
- name: Get installed version of Apache.
  shell: "{{ apache_daemon_path }}{{ apache_daemon }} -v"
  changed_when: false
  register: _apache_version

- name: Create apache_version variable.
  set_fact:
    apache_version: "{{ _apache_version.stdout.split()[2].split('/')[1] }}"

- include_vars: roles/geerlingguy.apache/vars/apache-22.yml
  when: "apache_version.split('.')[1] == '2'"

- include_vars: roles/geerlingguy.apache/vars/apache-24.yml
  when: "apache_version.split('.')[1] == '4'"

- name: deploy private keys
  copy:
    content: '{{ item.private }}'
    dest: "/etc/ssl/private/{{ item.name }}.key"
  with_items: "{{ apache_ssl_certificates }}"
  notify: restart apache

- name: deploy certificates
  copy:
    content: '{{ item.public }}'
    dest: "/etc/ssl/certs/{{ item.name }}.pem"
  with_items: "{{ apache_ssl_certificates }}"
  notify: restart apache

- name: deploy intermediate certificates
  copy:
    content: '{{ item.intermediate }}'
    dest: "/etc/ssl/certs/{{ item.name }}-intermediate.pem"
  with_items: "{{ apache_ssl_certificates }}"
  when: "'intermediate' in item"
  notify: restart apache

- name: Check whether certificates defined in vhosts exist.
  stat: 'path={{ item.certificate_file }}'
  register: apache_ssl_certificate_files
  with_items: '{{ apache_vhosts_ssl }}'

- name: Add apache vhost configuration files - HTTPS
  template:
    src: 'apache/vhost-ssl.conf.j2'
    dest: "{{ apache_conf_path }}/sites-available/{{ '%03d' | format(item.0) }}-https-{{ item.1.servername }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  with_indexed_items: '{{ apache_vhosts_ssl }}'
  when: 'not apache_create_vhosts'

- name: Add apache vhost configuration files - HTTP
  template:
    src: 'apache/vhost.conf.j2'
    dest: "{{ apache_conf_path }}/sites-available/{{ '%03d' | format(item.0 + 100) }}-http-{{ item.1.servername }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  with_indexed_items: '{{ apache_vhosts }}'
  when: 'not apache_create_vhosts'

- name: Add vhost symlink in sites-enabled - HTTPS
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ '%03d' | format(item.0) }}-https-{{ item.1.servername }}.conf"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ '%03d' | format(item.0) }}-https-{{ item.1.servername }}.conf"
    state: link
  notify: restart apache
  with_indexed_items: '{{ apache_vhosts_ssl }}'
  when: 'not apache_create_vhosts'

- name: Add vhost symlink in sites-enabled - HTTP
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ '%03d' | format(item.0 + 100) }}-http-{{ item.1.servername }}.conf"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ '%03d' | format(item.0 + 100) }}-http-{{ item.1.servername }}.conf"
    state: link
  notify: restart apache
  with_indexed_items: '{{ apache_vhosts }}'
  when: 'not apache_create_vhosts'
