---
- name: Ensure django-site directory exists
  file:
    path={{ django_site_root | mandatory }}
    state=directory
    recurse=yes
  tags: ['django']

- name: Create django group
  group:
    name=django
    system=yes
    state=present
  tags: ['django']

- name: Create django user
  user:
    name=django
    append=yes
    group=django
    home={{ django_site_root }}
    shell=/bin/bash
    system=yes
    state=present
  tags: ['django']

- name: Set django-site directory mode
  file:
    path={{ django_site_root | mandatory }}
    state=directory
    owner=django
    group=django
    mode=02775
  tags: ['django']

- name: Ensure django-site htdocs directory exists
  file:
    path={{ django_site_root }}/htdocs
    state=directory
    owner=django
    group=django
    mode=02775
  tags: ['django']

- name: Generate Google site verification file
  copy:
    dest: '{{ django_site_root }}/htdocs/google{{ google_site_verification_code }}.html'
    content: 'google-site-verification: google{{ google_site_verification_code }}.html'
    owner: django
    group: django
    mode: 0644
  when: google_site_verification_code is defined
  tags: ['django']

- name: Link media dir
  file:
    src=static/media
    dest={{ django_site_root | mandatory }}/media
    force=yes
    state=link
  tags: ['django']

- name: Repo-init the django manifest
  command: repo init -u {{ django_site_manifest_url | mandatory }}
    creates={{ django_site_root }}/.repo/manifest.xml
    chdir={{ django_site_root }}
  tags: ['django']

- name: Repo-sync the latest source tree
  command: repo sync
    chdir={{ django_site_root }}
  tags: ['django']

- name: Ensure dependencies are installed.
  apt: pkg={{ item }} state=installed
  with_items:
    - make
    - python-pip
    - libjpeg-dev
    - python-letsencrypt-apache
  tags: ['django']

- include: postgresql.yml

- name: Generate settings_local.py
  template: >
    src=django/settings_local.py.j2
    dest={{ django_site_root }}/site/project/settings_local.py
    owner=django
    group=django
    mode=0640
  tags: ['django']

- name: Remove .freeze.list
  file:
    path={{ django_site_root }}/.virtualenv/.freeze.list state=absent
  tags: ['django']

- name: Prepare database schema
  command: make prepare-db
    chdir={{ django_site_root }}/site
  environment:
    DJANGO_SETTINGS_MODULE: project.settings_local
  tags: ['django']

- name: Touch wsgi.py
  file:
    path={{ django_site_root }}/site/project/wsgi.py state=touch
  tags: ['django']

- include: apache.yml
