---
- name: Ensure django-site directory exists
  file: path={{ django_site_root }} state=directory

- name: Repo-init the django manifest
  command: repo init -u {{ django_site_manifest_url }}
    creates={{ django_site_root }}/.repo/manifest.xml
    chdir={{ django_site_root }}

- name: Repo-sync the latest source tree
  command: repo sync
    chdir={{ django_site_root }}
