---
- name: Create django group
  group:
    name=django
    system=yes
    state=present

- name: Create django user
  user:
    name=django
    append=yes
    group=django
    home={{ django_site_root }}
    shell=/bin/bash
    system=yes
    state=present

- name: Ensure django-site directory exists
  file:
    path={{ django_site_root | mandatory }}
    state=directory
    owner=django
    group=django
    mode=02775

- name: Repo-init the django manifest
  command: repo init -u {{ django_site_manifest_url | mandatory }}
    creates={{ django_site_root }}/.repo/manifest.xml
    chdir={{ django_site_root }}

- name: Repo-sync the latest source tree
  command: repo sync
    chdir={{ django_site_root }}

- name: Ensure dependencies are installed.
  apt: pkg=make state=installed

- include: postgresql.yml

- name: Generate settings_local.py
  template: >
    src=django/settings_local.py.j2
    dest={{ django_site_root }}/site/project/settings_local.py
    owner=django
    group=django
    mode=0600

- name: Prepare database schema
  command: make prepare-db
    chdir={{ django_site_root }}/site
  environment:
    DJANGO_SETTINGS_MODULE: project.settings_local
